// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	Bank          string
	BankAccount   string
	BankBranch    string
	Company       string
	CompanyClient string
	Invoice       string
	User          string
}{
	Bank:          "bank",
	BankAccount:   "bank_account",
	BankBranch:    "bank_branch",
	Company:       "company",
	CompanyClient: "company_client",
	Invoice:       "invoice",
	User:          "user",
}
