// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ryomak/invoice-api-example/application/usecase"
	"github.com/ryomak/invoice-api-example/infrastructure/client/db"
	"github.com/ryomak/invoice-api-example/presentation/handler"
	"github.com/ryomak/invoice-api-example/presentation/middleware"
)

// Injectors from wire.go:

func Handlers(conn *db.Conn) (*handler.Handler, error) {
	invoice := usecase.NewInvoice()
	invoiceHandler := handler.NewInvoiceHandler(invoice)
	handlerHandler := handler.New(invoiceHandler)
	return handlerHandler, nil
}

func Middlewares(conn *db.Conn) (*middleware.Middleware, error) {
	authMiddleware := middleware.NewAuthMiddleware()
	middlewareMiddleware := middleware.New(authMiddleware)
	return middlewareMiddleware, nil
}
